(function () {
  const opt = (id, text) => ({ id, text });
  const q = (id, topic, difficulty, focus, prompt, options, answer, explanation) => ({
    id,
    topic,
    difficulty,
    focus,
    prompt,
    options,
    answer,
    explanation,
  });

  const exams = [
    {
      id: "final-set-a",
      label: "A",
      title: "Final Exam Set A",
      description: "Balanced mixed final with conceptual interpretation, architecture choices, and pipeline reasoning across every required topic.",
      durationMinutes: 90,
      questions: [
        q("final-a-01", "unsupervised-learning", "Hard", "K-means scaling", "A team clusters users with K-means using annual income measured in dollars and app engagement measured on a 0 to 1 scale. The resulting clusters are driven almost entirely by income. Which change best addresses the most likely cause without changing the clustering algorithm?", [opt("A", "Increase k until the inertia curve visibly flattens"), opt("B", "Standardize the features before running K-means"), opt("C", "Use the same centroids but train for more iterations"), opt("D", "Initialize centroids with the highest-income users")], "B", "K-means with Euclidean distance is highly scale-sensitive. Standardizing prevents a large-range feature like income from dominating the distance geometry and therefore dominating the clusters."),
        q("final-a-02", "unsupervised-learning", "Hard", "Cluster geometry", "Which dataset shape is the clearest warning sign that standard K-means may produce a misleading partition even if the correct number of clusters is known?", [opt("A", "Two roughly spherical clouds with similar variance"), opt("B", "Two elongated crescent-shaped clouds wrapped around each other"), opt("C", "Three compact blobs with mild overlap"), opt("D", "One dense blob and one slightly larger dense blob")], "B", "K-means assumes clusters can be represented well by centroids and Voronoi-style partitions. Non-convex shapes such as two interlocking crescents violate that geometry even when k is chosen correctly."),
        q("final-a-03", "unsupervised-learning", "Medium", "Hierarchical clustering", "In an agglomerative dendrogram, what is the main effect of cutting the tree at a higher merge height?", [opt("A", "You obtain fewer, broader clusters"), opt("B", "You obtain more, finer clusters"), opt("C", "The centroids become more stable but the cluster count stays fixed"), opt("D", "The algorithm switches from local to global distance preservation")], "A", "A higher cut happens after more merges have already taken place, so it produces fewer clusters. Lower cuts keep more merges separated and therefore yield more clusters."),
        q("final-a-04", "unsupervised-learning", "Medium", "PCA meaning", "What does the first principal component represent?", [opt("A", "The feature that has the highest correlation with the label"), opt("B", "The direction in feature space capturing the most variance"), opt("C", "The cluster center with the lowest inertia"), opt("D", "The nonlinear manifold used by t-SNE to preserve neighborhoods")], "B", "PCA finds orthogonal directions of maximal variance. The first principal component is the single direction along which the projected data varies the most."),
        q("final-a-05", "unsupervised-learning", "Hard", "PCA before clustering", "Why can reducing data with PCA before clustering sometimes make cluster quality worse even when the first two principal components explain most variance?", [opt("A", "Because PCA always destroys Euclidean distance completely"), opt("B", "Because the low-variance directions can still contain the information that separates clusters"), opt("C", "Because K-means requires exactly the original number of features"), opt("D", "Because PCA forces all clusters to have equal size")], "B", "PCA preserves variance, not necessarily class or cluster separability. A low-variance direction can still be the direction that actually distinguishes groups, so discarding it can hurt clustering."),
        q("final-a-06", "unsupervised-learning", "Hard", "t-SNE interpretation", "A student concludes from a t-SNE plot that cluster A is 'twice as far' from cluster B as from cluster C. Why is this claim unsafe?", [opt("A", "t-SNE is supervised and therefore only meaningful with labels"), opt("B", "t-SNE mainly preserves local neighborhoods, not exact global distances"), opt("C", "t-SNE always outputs orthogonal axes with unit variance"), opt("D", "t-SNE is equivalent to PCA after whitening")], "B", "t-SNE is useful for visualizing local neighborhood structure, but global spacing can be highly distorted. Inter-cluster distances in the 2D map should not be treated as exact metric statements."),

        q("final-a-07", "neural-networks-foundations", "Hard", "Need for nonlinearity", "Why do stacked linear layers without nonlinear activations fail to realize the usual advantage of depth?", [opt("A", "Because the gradients cannot be computed through more than one layer"), opt("B", "Because the composition of linear maps is still a single linear map"), opt("C", "Because linear layers cannot contain bias terms"), opt("D", "Because linear layers only work for binary classification")], "B", "Without nonlinearities, multiple affine or linear transformations collapse into one equivalent affine transformation. Depth then adds parameters but not genuinely richer function classes."),
        q("final-a-08", "neural-networks-foundations", "Medium", "Output and loss matching", "You need a network for single-label classification among five mutually exclusive classes. Which output and loss pairing is the standard choice?", [opt("A", "Linear output with mean squared error"), opt("B", "Five independent sigmoids with mean squared error"), opt("C", "Softmax output with cross-entropy loss"), opt("D", "ReLU output with hinge loss by default")], "C", "Softmax produces a normalized class distribution over mutually exclusive classes, and cross-entropy measures how much probability mass the model assigns to the correct class."),
        q("final-a-09", "neural-networks-foundations", "Hard", "Cross-entropy behavior", "Why does cross-entropy usually punish a confidently wrong classifier more strongly than a weakly wrong classifier?", [opt("A", "Because it grows with the negative log probability assigned to the true class"), opt("B", "Because it clips all probabilities below 0.5 to zero"), opt("C", "Because it ignores the predicted class and only uses the hidden activations"), opt("D", "Because it is computed after dropout, not before")], "A", "Cross-entropy depends on the log probability of the correct class. If the model assigns extremely low probability to the truth, the negative log becomes very large, so confident mistakes are penalized heavily."),
        q("final-a-10", "neural-networks-foundations", "Hard", "Backpropagation", "What is the key computational idea behind backpropagation?", [opt("A", "It estimates gradients by repeatedly flipping the sign of each weight"), opt("B", "It reuses local derivatives through the chain rule instead of recomputing full derivatives independently"), opt("C", "It replaces all nonlinearities with linear approximations during training"), opt("D", "It makes the loss convex by passing errors backward")], "B", "Backpropagation is an efficient application of the chain rule through a computational graph. Intermediate derivatives are reused so gradient computation scales to large layered models."),
        q("final-a-11", "neural-networks-foundations", "Medium", "Learning rate", "What behavior most strongly suggests that the learning rate is too large?", [opt("A", "Training and validation losses both decrease steadily"), opt("B", "The optimization oscillates or diverges instead of settling downward"), opt("C", "The model memorizes the training set with near-zero error"), opt("D", "The hidden units remain nonlinear during training")], "B", "An overly large learning rate can overshoot good regions of the loss surface. The visible symptom is unstable optimization: bouncing, divergence, or loss values that fail to settle."),
        q("final-a-12", "neural-networks-foundations", "Hard", "Dropout", "Which statement about dropout is most accurate?", [opt("A", "It removes the need for a validation set"), opt("B", "It randomly suppresses units during training to reduce co-adaptation, but inference uses the full network with appropriate scaling"), opt("C", "It is only useful in regression and not in classification"), opt("D", "It changes the target labels to make the task harder")], "B", "Dropout acts as a regularizer by forcing the network not to rely too much on any single unit. During inference, units are not randomly dropped, and the network uses the learned weights in a scaled or expectation-matched form."),

        q("final-a-13", "convolutional-networks", "Medium", "Why CNNs fit images", "Why are CNNs usually a better starting point than plain dense networks for images?", [opt("A", "Because CNNs assume every pixel is independent"), opt("B", "Because CNNs exploit locality and reuse the same filters across spatial positions"), opt("C", "Because CNNs cannot overfit as easily as any other architecture"), opt("D", "Because CNNs never require nonlinear activations")], "B", "Images have local spatial structure, and the same kind of edge or texture can appear in many positions. Convolution encodes that inductive bias through local receptive fields and parameter sharing."),
        q("final-a-14", "convolutional-networks", "Hard", "Output size computation", "A convolution layer receives a 32 x 32 input, uses filter size 5, padding 2, stride 1, and dilation 1. What is the spatial output size?", [opt("A", "28 x 28"), opt("B", "30 x 30"), opt("C", "32 x 32"), opt("D", "34 x 34")], "C", "Using the standard convolution size formula, padding 2 exactly offsets the border loss from a 5 x 5 filter at stride 1. The layer preserves spatial size at 32 x 32."),
        q("final-a-15", "convolutional-networks", "Hard", "1 x 1 convolution", "What is the main purpose of a 1 x 1 convolution in a CNN block?", [opt("A", "To enlarge the spatial receptive field more than a 3 x 3 filter"), opt("B", "To mix information across channels at each spatial location"), opt("C", "To perform max pooling in a differentiable way"), opt("D", "To force the output to be grayscale")], "B", "A 1 x 1 convolution looks at each spatial location separately but learns a weighted combination across channels. It is therefore especially useful for channel projection, mixing, and bottleneck designs."),
        q("final-a-16", "convolutional-networks", "Medium", "Receptive field growth", "Why can stacking several small convolutions be preferable to using one huge convolution immediately?", [opt("A", "Because small convolutions reduce parameters while still growing the effective receptive field and adding more nonlinear stages"), opt("B", "Because small convolutions make the network exactly linear"), opt("C", "Because only large convolutions can share parameters across locations"), opt("D", "Because large convolutions cannot be trained with backpropagation")], "A", "Multiple small filters such as stacked 3 x 3 layers can build a large effective receptive field with fewer parameters than one large filter. They also insert extra nonlinearities between stages, increasing representational power."),
        q("final-a-17", "convolutional-networks", "Hard", "Residual connections", "What is the main optimization benefit of a residual skip connection?", [opt("A", "It guarantees zero training loss on any image task"), opt("B", "It lets a block learn a refinement relative to its input and helps gradients flow through very deep networks"), opt("C", "It removes the need for normalization and activation functions"), opt("D", "It forces all convolutions to use identical filters")], "B", "Residual learning makes it easier for deep stacks to preserve useful information and to learn changes on top of an identity path. This stabilizes optimization and reduces degradation as networks become very deep."),
        q("final-a-18", "convolutional-networks", "Medium", "Transfer learning strategy", "When is freezing many early layers of a pretrained CNN most reasonable?", [opt("A", "When the target dataset is small and visually similar to the source domain"), opt("B", "When the target dataset is huge and completely unrelated to the source domain"), opt("C", "When the model underfits because it has too many trainable parameters"), opt("D", "When the final task requires no visual features at all")], "A", "Early CNN layers often learn generic edges and textures that transfer well. If target data is limited and the domain is similar, freezing more layers can reduce overfitting while preserving useful pretrained features."),

        q("final-a-19", "recommendation-systems", "Medium", "Content-based recommendation", "Which situation most strongly favors a content-based recommender?", [opt("A", "New items arrive often, but rich item metadata is available"), opt("B", "The system has no item features but decades of dense user-item ratings"), opt("C", "Every user has already rated almost every item"), opt("D", "The ranking metric does not care about item semantics")], "A", "Content-based systems can recommend new items as long as their features are available, even before enough interaction history accumulates. That makes them especially helpful for item cold start."),
        q("final-a-20", "recommendation-systems", "Medium", "Collaborative filtering", "Why can collaborative filtering recommend a movie even when the system has no hand-engineered metadata about the movie itself?", [opt("A", "Because it infers structure from patterns of user-item interactions"), opt("B", "Because it converts all users into convolution filters"), opt("C", "Because it only needs the movie title length"), opt("D", "Because collaborative filtering assumes all items are equally similar")], "A", "Collaborative filtering uses the interaction matrix itself as the signal. If people who liked one set of items also liked another item, the model can exploit that behavioral pattern without explicit content features."),
        q("final-a-21", "recommendation-systems", "Hard", "Implicit feedback", "In an implicit-feedback recommender, why is a missing click not automatically equivalent to dislike?", [opt("A", "Because user behavior logs are usually symmetric around zero"), opt("B", "Because non-interaction may reflect lack of exposure, timing, or attention rather than negative preference"), opt("C", "Because clicks can only be used in supervised classification"), opt("D", "Because recommendation models ignore missing entries entirely")], "B", "Implicit data is ambiguous. A user may fail to click simply because they never saw the item, were distracted, or had no immediate need, not because they actively disliked it."),
        q("final-a-22", "recommendation-systems", "Hard", "Matrix factorization", "What does the dot product in a basic matrix factorization recommender represent?", [opt("A", "The Euclidean distance between raw item features"), opt("B", "The agreement between user and item latent factors"), opt("C", "The number of ratings the user has given in total"), opt("D", "The precision@k of the ranking model")], "B", "Matrix factorization learns low-dimensional latent vectors for users and items. The dot product is large when a user's latent preferences align well with an item's latent attributes."),
        q("final-a-23", "recommendation-systems", "Hard", "Evaluation", "Why is plain classification accuracy often a poor primary metric for recommendation?", [opt("A", "Because recommendation systems never use labels"), opt("B", "Because what matters most is the quality and ordering of the top-ranked items rather than average correctness over many trivial negatives"), opt("C", "Because accuracy can only be computed for regression tasks"), opt("D", "Because recommenders do not produce scores or probabilities")], "B", "Recommendation is fundamentally a ranking problem, especially near the top of the list where user attention is scarce. Accuracy can look high even when the few surfaced items are poor."),
        q("final-a-24", "recommendation-systems", "Medium", "Industrial pipeline", "What is the usual role split between candidate generation and ranking in a large-scale recommender?", [opt("A", "Candidate generation explains the model; ranking collects the data"), opt("B", "Candidate generation narrows the catalog quickly; ranking applies a slower, richer model to the short list"), opt("C", "Candidate generation is only used for images; ranking only for text"), opt("D", "Both stages usually use the exact same features and objective for no particular reason")], "B", "Large catalogs are too expensive to score fully with a heavy model. A fast retrieval stage proposes candidates, and a more expressive ranking stage then sorts those candidates carefully."),

        q("final-a-25", "sequence-models", "Hard", "Long-range dependencies", "Why do plain RNNs struggle with very long-range dependencies?", [opt("A", "Because they cannot process more than one token at a time"), opt("B", "Because repeated Jacobian multiplications can cause gradients to vanish or explode across many time steps"), opt("C", "Because they do not use matrix multiplication"), opt("D", "Because recurrence removes all nonlinearity from the network")], "B", "Training long recurrent chains means backpropagating through many repeated transformations. If those derivatives repeatedly shrink or grow, information about far-away dependencies becomes numerically unstable."),
        q("final-a-26", "sequence-models", "Medium", "LSTM gates", "What is the most direct role of the forget gate in an LSTM?", [opt("A", "It decides how much of the previous cell state to retain"), opt("B", "It reorders the sequence before encoding"), opt("C", "It normalizes the attention weights"), opt("D", "It converts the hidden state into a probability distribution")], "A", "The forget gate scales the old cell state before it is carried forward. This allows the model to keep useful memory or discard stale information when context changes."),
        q("final-a-27", "sequence-models", "Hard", "Teacher forcing", "What happens during teacher forcing in sequence-to-sequence training?", [opt("A", "The decoder receives its own sampled output as the next input even during training"), opt("B", "The decoder is given the true previous token as context during training"), opt("C", "The encoder is removed and replaced by a convolutional block"), opt("D", "The model trains without any loss function on intermediate tokens")], "B", "Teacher forcing reduces training instability by feeding the correct previous token at each step. This differs from inference, where the model must condition on its own earlier outputs."),
        q("final-a-28", "sequence-models", "Hard", "Attention mechanism", "In scaled dot-product attention, what determines how strongly a key-value pair influences a given query?", [opt("A", "The norm of the value vector alone"), opt("B", "The similarity between the query and key before the softmax weighting"), opt("C", "The sequence length alone"), opt("D", "The dropout probability applied to the hidden state")], "B", "Attention scores are based on query-key compatibility. After scaling and softmax, these scores become weights that determine how much each value contributes to the query's output."),
        q("final-a-29", "sequence-models", "Medium", "Self-attention advantage", "Why is self-attention often said to model long-range dependencies more directly than recurrence?", [opt("A", "Because every token can connect to every other token in one layer instead of passing information through many time steps"), opt("B", "Because self-attention eliminates the need for matrix multiplications"), opt("C", "Because self-attention only works on short sequences"), opt("D", "Because self-attention is always linear in sequence length")], "A", "In a recurrent model, distant tokens interact through long chains of state updates. Self-attention allows direct pairwise interaction, reducing path length between distant positions."),
        q("final-a-30", "sequence-models", "Medium", "Positional information", "Why do Transformer encoders need some form of positional information?", [opt("A", "Because attention by itself has no built-in notion of token order"), opt("B", "Because the softmax cannot be computed without sequence indices"), opt("C", "Because embeddings already encode order too strongly"), opt("D", "Because recurrence must be simulated token by token")], "A", "Self-attention over a set of token embeddings is permutation-equivariant unless order is injected explicitly. Positional encodings or learned position embeddings tell the model where each token occurs."),

        q("final-a-31", "generative-ai", "Medium", "Language-model objective", "What is the core pretraining objective of an autoregressive language model?", [opt("A", "Predict the entire paragraph in one step from random noise"), opt("B", "Predict the next token given the previous context"), opt("C", "Predict which cluster a sentence belongs to under K-means"), opt("D", "Predict the hidden state of the encoder from the decoder output")], "B", "Autoregressive language models factor a sequence into next-token conditional probabilities. Training repeatedly asks the model to estimate the next token given the prefix."),
        q("final-a-32", "generative-ai", "Medium", "Decoding choices", "What is the clearest contrast between greedy decoding and top-p sampling?", [opt("A", "Greedy always samples from the entire vocabulary; top-p uses beam search"), opt("B", "Greedy always picks the highest-probability token; top-p samples from a truncated high-mass set"), opt("C", "Greedy only works for diffusion models; top-p only for RNNs"), opt("D", "Greedy requires RLHF; top-p requires LoRA")], "B", "Greedy decoding is deterministic and always chooses the most likely next token. Top-p sampling first keeps the smallest token set whose cumulative probability exceeds p and then samples from that set."),
        q("final-a-33", "generative-ai", "Hard", "Alignment pipeline", "How does instruction tuning differ most directly from RLHF?", [opt("A", "Instruction tuning uses supervised instruction-response pairs; RLHF further optimizes behavior using human preference signals"), opt("B", "Instruction tuning changes tokenization; RLHF changes the optimizer only"), opt("C", "Instruction tuning retrieves documents; RLHF compresses them"), opt("D", "Instruction tuning is only for images; RLHF only for text search")], "A", "Instruction tuning teaches the model to follow prompts using labeled demonstrations. RLHF is an additional alignment stage that pushes outputs toward human-preferred behavior beyond simple supervised imitation."),
        q("final-a-34", "generative-ai", "Hard", "RAG versus LoRA", "Which statement best distinguishes RAG from LoRA?", [opt("A", "RAG changes model weights cheaply; LoRA retrieves external passages at inference"), opt("B", "RAG injects external retrieved evidence at inference; LoRA adds trainable low-rank adapters for parameter-efficient fine-tuning"), opt("C", "RAG is only for image generation; LoRA only for text classification"), opt("D", "RAG and LoRA are two names for the same alignment method")], "B", "RAG changes the model's available context at inference by retrieving documents. LoRA instead modifies the model through small trainable adapters while keeping the base model mostly frozen."),
        q("final-a-35", "generative-ai", "Hard", "Inference efficiency", "Why does a KV cache make autoregressive decoding faster?", [opt("A", "It stores earlier keys and values so the model does not recompute attention over the whole prefix from scratch at every step"), opt("B", "It stores the final answer before decoding starts"), opt("C", "It replaces the tokenizer with a compressed lookup table"), opt("D", "It converts sampling into greedy decoding automatically")], "A", "During autoregressive decoding, each new token attends to the earlier context. Caching previous attention keys and values avoids recomputing those earlier representations for every new step."),
        q("final-a-36", "generative-ai", "Hard", "Diffusion models", "What is the model actually trained to do in the reverse direction of a diffusion process?", [opt("A", "Classify whether the current image is safe or unsafe"), opt("B", "Map the image directly to a final caption in one pass"), opt("C", "Predict or remove the noise component so a clean sample can be recovered gradually"), opt("D", "Choose the best cluster centroid for the image")], "C", "Forward diffusion gradually destroys structure by adding noise. The learned reverse process predicts how to denoise step by step so a clean sample can emerge from noise."),
      ],
    },
    {
      id: "final-set-b",
      label: "B",
      title: "Final Exam Set B",
      description: "More troubleshooting-heavy mixed final emphasizing failure modes, interpretation, metric choice, and architectural tradeoffs.",
      durationMinutes: 90,
      questions: [
        q("final-b-01", "unsupervised-learning", "Hard", "Choosing k", "Why does an elbow plot based only on K-means inertia fail to provide an automatic mathematically exact value of k in many real problems?", [opt("A", "Because inertia often decreases smoothly as k increases, so the elbow can be ambiguous"), opt("B", "Because inertia is undefined for Euclidean distance"), opt("C", "Because K-means forces inertia to remain constant after three clusters"), opt("D", "Because inertia only works for supervised labels")], "A", "Inertia almost always drops as more clusters are added, sometimes without a sharp bend. The elbow is a heuristic rather than a guaranteed criterion with a unique optimum."),
        q("final-b-02", "unsupervised-learning", "Hard", "Linkage behavior", "Which linkage choice is most associated with the chaining effect, where clusters can merge through thin bridges of nearby points?", [opt("A", "Single linkage"), opt("B", "Complete linkage"), opt("C", "Average linkage"), opt("D", "Ward linkage")], "A", "Single linkage uses the closest pair of points between clusters. That makes it very sensitive to chain-like bridges and can create long, strung-out clusters."),
        q("final-b-03", "unsupervised-learning", "Hard", "PCA reconstruction", "What optimization perspective best describes standard PCA?", [opt("A", "It finds a low-dimensional linear subspace that minimizes squared reconstruction error"), opt("B", "It directly maximizes cluster purity after projection"), opt("C", "It exactly preserves all pairwise distances"), opt("D", "It preserves only the class label information and ignores variance")], "A", "PCA can be viewed as choosing a low-rank linear subspace that reconstructs the data as well as possible in the squared-error sense. The variance-maximization and reconstruction-error views are equivalent."),
        q("final-b-04", "unsupervised-learning", "Medium", "Linearity of PCA", "Which statement about PCA is correct?", [opt("A", "Its axes can be arbitrary nonlinear curves through the feature space"), opt("B", "Its principal components are orthogonal linear combinations of the original features"), opt("C", "It is a centroid-based clustering algorithm"), opt("D", "It is mainly used to preserve exact nearest-neighbor rankings under any metric")], "B", "PCA is a linear method. Each principal component is a direction formed by a weighted linear combination of original features, constrained to be orthogonal to earlier components."),
        q("final-b-05", "unsupervised-learning", "Hard", "t-SNE perplexity intuition", "What does the perplexity setting in t-SNE most closely control in practice?", [opt("A", "The number of principal components used before projection"), opt("B", "The effective neighborhood scale each point pays attention to"), opt("C", "The number of labels the method can visualize"), opt("D", "The exact global distance preservation error")], "B", "Perplexity acts like a neighborhood-size scale parameter. It influences how local versus broader relationships are balanced in the similarity distributions that t-SNE tries to match."),
        q("final-b-06", "unsupervised-learning", "Medium", "Cosine similarity", "Why is cosine similarity often more natural than Euclidean distance for high-dimensional text-like embeddings?", [opt("A", "Because cosine focuses on vector direction rather than magnitude"), opt("B", "Because cosine guarantees spherical clusters"), opt("C", "Because cosine is identical to PCA on normalized data"), opt("D", "Because cosine makes dimensionality reduction unnecessary")], "A", "In many embedding settings, direction represents semantic meaning more strongly than overall magnitude. Cosine similarity compares angle, so it emphasizes orientation rather than raw length."),

        q("final-b-07", "neural-networks-foundations", "Hard", "Perceptron limits", "Why can a single perceptron not solve XOR?", [opt("A", "Because XOR requires at least two output neurons"), opt("B", "Because XOR is not linearly separable"), opt("C", "Because XOR has too many training examples"), opt("D", "Because XOR requires recurrent memory")], "B", "A single perceptron implements a linear decision boundary. XOR requires a nonlinear separation pattern, so at least a multilayer network with nonlinearity is needed."),
        q("final-b-08", "neural-networks-foundations", "Hard", "ReLU failure mode", "What is the usual concern behind 'dead ReLUs'?", [opt("A", "Units that stay on the positive linear branch for all inputs"), opt("B", "Units whose preactivations remain negative so they output zero and receive little or no useful gradient"), opt("C", "Units that make the softmax probabilities sum to more than one"), opt("D", "Units that only appear in convolutional networks")], "B", "A ReLU outputs zero for negative inputs. If a unit gets stuck in a regime where it is almost always negative, it can effectively stop participating in learning."),
        q("final-b-09", "neural-networks-foundations", "Medium", "Softmax properties", "What is the defining property of a softmax output layer in single-label multiclass classification?", [opt("A", "Each class score is thresholded independently between -1 and 1"), opt("B", "The output values are nonnegative and sum to one across classes"), opt("C", "The output must be exactly sparse with one nonzero class"), opt("D", "The output is a reconstruction of the input image")], "B", "Softmax converts logits into a normalized probability distribution over classes. That makes it especially suitable when exactly one class is the intended label."),
        q("final-b-10", "neural-networks-foundations", "Medium", "Regression loss", "Why is mean squared error a natural loss for scalar regression problems?", [opt("A", "Because it compares predicted continuous values directly against continuous targets"), opt("B", "Because it forces probabilities to sum to one"), opt("C", "Because it only works when labels are binary"), opt("D", "Because it estimates nearest-neighbor structure")], "A", "Regression predicts numeric targets, and mean squared error penalizes numerical deviation directly. Its geometry also aligns with Gaussian noise assumptions in many settings."),
        q("final-b-11", "neural-networks-foundations", "Hard", "Mini-batch SGD", "Why is mini-batch stochastic gradient descent commonly preferred over full-batch gradient descent in deep learning?", [opt("A", "It uses only one fixed example forever"), opt("B", "It is computationally efficient on hardware and introduces gradient noise that can still permit learning progress"), opt("C", "It makes the objective convex"), opt("D", "It removes the need for shuffling data")], "B", "Mini-batches exploit vectorized hardware well and update parameters more frequently than full-batch training. The noise in their gradients can also help exploration of the loss landscape."),
        q("final-b-12", "neural-networks-foundations", "Hard", "Early stopping", "Why is early stopping often described as a form of regularization?", [opt("A", "It prevents the network from ever seeing the training data"), opt("B", "It halts training when validation behavior suggests the model is beginning to overfit"), opt("C", "It changes cross-entropy into mean squared error"), opt("D", "It turns a nonlinear model into a linear one")], "B", "Early stopping constrains how far the optimizer is allowed to fit the training data. Stopping near the point where validation performance peaks often improves generalization."),

        q("final-b-13", "convolutional-networks", "Medium", "Padding purpose", "What is a major reason to add padding in convolutional networks?", [opt("A", "To reduce every output map to a single scalar"), opt("B", "To preserve more border information and sometimes preserve spatial size"), opt("C", "To remove all nonlinearities from the network"), opt("D", "To make every filter act like max pooling")], "B", "Without padding, border pixels are used less often and spatial size shrinks quickly. Padding helps keep edge information and can maintain output dimensions when desired."),
        q("final-b-14", "convolutional-networks", "Medium", "Pooling effect", "What is the usual role of max pooling?", [opt("A", "To rotate the image into the latent space"), opt("B", "To downsample while keeping the strongest local activation in each pooling region"), opt("C", "To replace all convolutions with matrix factorization"), opt("D", "To convert a regression task into classification")], "B", "Max pooling reduces spatial resolution and keeps the dominant local response. This can improve computational efficiency and modest local translation robustness."),
        q("final-b-15", "convolutional-networks", "Hard", "Batch normalization", "Why does batch normalization often make deep networks easier to optimize?", [opt("A", "It fixes the labels so they cannot drift during training"), opt("B", "It stabilizes internal activation distributions and often supports larger or more reliable learning dynamics"), opt("C", "It removes the need for any nonlinearity"), opt("D", "It ensures zero training error in the first epoch")], "B", "Batch normalization reduces internal covariate shift in a practical sense by normalizing activations and then learning affine corrections. This often leads to smoother optimization and more stable gradients."),
        q("final-b-16", "convolutional-networks", "Hard", "Depthwise separable convolution", "Why is a depthwise separable convolution cheaper than a standard full convolution?", [opt("A", "Because it separates spatial filtering from channel mixing instead of learning both jointly in one expensive kernel bank"), opt("B", "Because it avoids all matrix multiplication"), opt("C", "Because it uses no learnable parameters"), opt("D", "Because it must operate on grayscale images only")], "A", "A standard convolution mixes channels and spatial structure simultaneously. Depthwise separable designs first apply per-channel spatial filters and then use pointwise mixing, which reduces computation and parameter count."),
        q("final-b-17", "convolutional-networks", "Hard", "Dilated convolution", "What is the main effect of dilation in a convolution layer?", [opt("A", "It reduces the number of channels to one"), opt("B", "It increases the receptive field without requiring a proportionally larger kernel"), opt("C", "It disables parameter sharing across locations"), opt("D", "It forces the stride to become one")], "B", "Dilation spaces filter taps apart. This allows the layer to cover a wider effective area while keeping the nominal kernel size and number of parameters relatively modest."),
        q("final-b-18", "convolutional-networks", "Medium", "Data augmentation", "Why is label-preserving data augmentation useful in image classification?", [opt("A", "It creates new exact labels from scratch"), opt("B", "It exposes the model to plausible variations of the same underlying class, reducing over-reliance on accidental details"), opt("C", "It guarantees the model will never overfit"), opt("D", "It removes the need for a validation set")], "B", "Augmentation teaches invariances and robustness by showing the model that certain transformations should not change the label. This often improves generalization when real data is limited."),

        q("final-b-19", "recommendation-systems", "Medium", "Neighborhood methods", "User-user and item-item collaborative filtering have what central idea in common?", [opt("A", "They recommend by exploiting similarity patterns in interaction behavior"), opt("B", "They only work when item metadata is abundant"), opt("C", "They always outperform latent-factor models on sparse data"), opt("D", "They ignore historical interactions and focus only on titles")], "A", "Both methods rely on similarity computed from behavior. They differ in whether the neighborhood is built around similar users or similar items, but the shared principle is interaction-driven analogy."),
        q("final-b-20", "recommendation-systems", "Hard", "Baseline biases", "In a baseline rating model, what do the user bias and item bias terms mainly capture?", [opt("A", "Whether the optimizer converges in one epoch"), opt("B", "Systematic tendencies such as generous users or broadly popular items"), opt("C", "The exact latent factor geometry of every item"), opt("D", "The NDCG of the final ranking")], "B", "A baseline model separates global average rating from user and item deviations. This captures simple but powerful effects such as some users rating high on average and some items receiving high ratings from almost everyone."),
        q("final-b-21", "recommendation-systems", "Medium", "User cold start", "A completely new user arrives with no click history. Which strategy is most directly helpful at the beginning?", [opt("A", "Pure matrix factorization with no priors or side information"), opt("B", "Collect some onboarding preferences or side information before relying heavily on collaborative signals"), opt("C", "Assume the user dislikes all unseen items"), opt("D", "Evaluate only with training accuracy")], "B", "New users provide little collaborative signal. Lightweight onboarding, content features, or popularity priors help bootstrap the recommender until behavior history accumulates."),
        q("final-b-22", "recommendation-systems", "Hard", "Ranking metrics", "Why can recall@k and precision@k tell different stories about the same recommender?", [opt("A", "Because one cares about how many relevant items were found while the other cares about how pure the top-k list is"), opt("B", "Because recall@k is only for regression and precision@k only for classification"), opt("C", "Because both metrics are mathematically identical"), opt("D", "Because neither metric depends on the chosen k")], "A", "Precision@k measures how many of the shown items are relevant, while recall@k measures how much of the relevant set has been recovered. A system can surface a very pure top list yet still miss many relevant items overall."),
        q("final-b-23", "recommendation-systems", "Hard", "Latent factors", "Why is matrix factorization often described as learning tastes rather than memorizing item IDs?", [opt("A", "Because it maps users and items into shared low-dimensional latent spaces whose alignments capture preference structure"), opt("B", "Because it stores one separate neural network for every item"), opt("C", "Because it discards user history once training finishes"), opt("D", "Because it does not use any numerical optimization")], "A", "Latent-factor models compress interaction patterns into hidden dimensions that often correspond to abstract taste factors. Recommendation then depends on how user and item factors align in that learned space."),
        q("final-b-24", "recommendation-systems", "Medium", "Popularity bias", "Why is popularity bias a serious product concern in recommender systems?", [opt("A", "Because it can create feedback loops that keep exposing already popular items while suppressing discovery"), opt("B", "Because popular items cannot be modeled with embeddings"), opt("C", "Because users always prefer only niche items"), opt("D", "Because popularity bias makes ranking metrics impossible to compute")], "A", "If a system mostly recommends already popular items, those items gain even more interactions and remain dominant. This can reduce catalog coverage, fairness, and user discovery."),

        q("final-b-25", "sequence-models", "Hard", "Encoder bottleneck", "Why was the fixed-size encoder bottleneck in early seq2seq systems a problem for long inputs?", [opt("A", "Because long sequences need a hidden state for each class label"), opt("B", "Because compressing all source information into one vector can lose fine-grained details needed later by the decoder"), opt("C", "Because the decoder cannot backpropagate through more than one token"), opt("D", "Because long inputs make softmax undefined")], "B", "When the entire source must be summarized in one vector, the decoder may not retain enough detailed information, especially for long or information-dense sequences. Attention reduced that bottleneck by letting the decoder revisit source states."),
        q("final-b-26", "sequence-models", "Medium", "Bidirectional models", "Why is a bidirectional encoder-style recurrent model not directly appropriate for ordinary left-to-right autoregressive generation?", [opt("A", "Because it can incorporate future context that would not be available at generation time"), opt("B", "Because it has no parameters"), opt("C", "Because it cannot process embeddings"), opt("D", "Because it forbids attention")], "A", "Bidirectional encoders are excellent when the whole sequence is available. Autoregressive generation, however, must produce token t without looking at future tokens t+1 and beyond."),
        q("final-b-27", "sequence-models", "Hard", "Multi-head attention", "What is a key motivation for multi-head attention?", [opt("A", "It lets the model attend to different types of relationships or subspaces in parallel"), opt("B", "It removes the need for positional encoding"), opt("C", "It guarantees interpretability of every head"), opt("D", "It forces all heads to learn identical weight patterns")], "A", "Different heads can specialize in different relational patterns such as syntax, locality, or long-distance reference. Multi-head structure broadens representational flexibility relative to a single attention map."),
        q("final-b-28", "sequence-models", "Hard", "Cross-attention", "In an encoder-decoder Transformer, what is the role of cross-attention in the decoder?", [opt("A", "It lets the decoder consult encoded source representations while generating target tokens"), opt("B", "It normalizes the source embeddings to unit variance"), opt("C", "It predicts the training labels for the encoder"), opt("D", "It removes the causal mask from decoder self-attention")], "A", "Cross-attention ties generation to the input sequence by allowing decoder queries to look up relevant encoder keys and values. This is crucial in tasks like translation or summarization."),
        q("final-b-29", "sequence-models", "Hard", "Exposure bias", "What is the usual meaning of exposure bias in sequence generation?", [opt("A", "The model is evaluated only on examples it has memorized"), opt("B", "During training the model sees gold previous tokens, but at inference it must condition on its own potentially erroneous outputs"), opt("C", "The encoder is exposed to too many convolution layers"), opt("D", "The hidden state is always exposed to dropout at test time")], "B", "Teacher forcing creates a train-test mismatch: training contexts are cleaner than inference contexts. Errors at test time can therefore cascade because the model was not trained primarily on its own imperfect histories."),
        q("final-b-30", "sequence-models", "Medium", "Transformer scaling", "Why do Transformers scale especially well on modern hardware compared with purely recurrent models?", [opt("A", "Because self-attention permits more parallel computation across sequence positions during training"), opt("B", "Because Transformers never use matrix multiplication"), opt("C", "Because Transformers require no memory for activations"), opt("D", "Because recurrence is mathematically impossible on GPUs")], "A", "RNNs impose a sequential dependency along time steps during training. Transformer blocks compute many token interactions in parallel, which fits modern accelerators well."),

        q("final-b-31", "generative-ai", "Medium", "Tokenization", "Why are subword tokenizers attractive for large language models?", [opt("A", "They eliminate the need for embeddings"), opt("B", "They can represent common words compactly while still handling rare words by decomposition"), opt("C", "They ensure every word is one token"), opt("D", "They force all languages to share the same syntax")], "B", "Subword tokenization balances vocabulary size and flexibility. Frequent terms can be efficient, while unseen or rare words can still be expressed as combinations of smaller units."),
        q("final-b-32", "generative-ai", "Hard", "In-context learning", "What is in-context learning?", [opt("A", "Updating model weights online after every prompt"), opt("B", "Changing task behavior using instructions or examples placed in the prompt without updating model parameters"), opt("C", "Retrieving nearest-neighbor images from a database"), opt("D", "Replacing the tokenizer during inference")], "B", "In-context learning uses the prompt itself as temporary task conditioning. The model adapts behavior from examples or instructions in context, but its weights remain unchanged."),
        q("final-b-33", "generative-ai", "Medium", "Temperature", "What does increasing temperature in decoding typically do?", [opt("A", "It sharpens the distribution so the model becomes more deterministic"), opt("B", "It flattens the distribution, usually increasing randomness and diversity"), opt("C", "It disables the softmax entirely"), opt("D", "It changes the training objective from autoregressive to denoising")], "B", "Temperature rescales logits before sampling. Higher temperature makes probabilities more even, which tends to increase diversity but also raises the chance of weaker choices."),
        q("final-b-34", "generative-ai", "Hard", "Limits of RLHF", "Why does RLHF not by itself guarantee factual accuracy?", [opt("A", "Because human preference optimization is not the same thing as perfect truth-tracking"), opt("B", "Because RLHF can only be applied to image models"), opt("C", "Because RLHF deletes the pretrained knowledge in the base model"), opt("D", "Because RLHF makes the model incapable of using documents")], "A", "RLHF aligns outputs with preferences such as helpfulness or harmlessness, but humans may prefer fluent or persuasive answers that are still wrong. Factuality often requires grounding, retrieval, or separate evaluation mechanisms."),
        q("final-b-35", "generative-ai", "Hard", "Tool use", "What is the advantage of letting a language model call a tool through a structured interface such as MCP?", [opt("A", "It gives the model access to external capabilities or fresh state instead of requiring everything to live in static weights"), opt("B", "It turns every prompt into supervised fine-tuning"), opt("C", "It removes the need for tokenization"), opt("D", "It guarantees that the model will never hallucinate")], "A", "Tool use extends a model beyond its frozen parameters by allowing retrieval, execution, or integration with external systems. It does not solve every reasoning problem, but it can supply current information and reliable actions."),
        q("final-b-36", "generative-ai", "Medium", "Guardrails", "What is the main role of guardrails in a generative AI system?", [opt("A", "To replace the base model with a clustering algorithm"), opt("B", "To add policy, moderation, or workflow controls around generation so risky outputs are less likely to be produced or acted on"), opt("C", "To force beam search during every response"), opt("D", "To convert text models into recommendation systems")], "B", "Guardrails are system-level safety measures such as moderation, refusal logic, schema checks, or tool restrictions. They complement the model rather than replacing its underlying generation mechanism."),
      ],
    },
    {
      id: "final-set-c",
      label: "C",
      title: "Final Exam Set C",
      description: "Integrated final with scenario-based questions, comparisons, and optimization or evaluation judgments across the full exam scope.",
      durationMinutes: 95,
      questions: [
        q("final-c-01", "unsupervised-learning", "Hard", "PCA preprocessing", "A dataset includes one feature measured in millimeters and another in kilometers. Why is standardization often important before PCA?", [opt("A", "Because PCA is supervised and needs balanced labels"), opt("B", "Because otherwise the large-scale feature can dominate the variance structure regardless of real importance"), opt("C", "Because PCA requires every feature to be binary"), opt("D", "Because standardization makes PCA nonlinear")], "B", "PCA follows variance. If one feature has a huge numeric scale, it may dominate the covariance structure even when it is not intrinsically the most informative dimension."),
        q("final-c-02", "unsupervised-learning", "Hard", "Complete linkage intuition", "Compared with single linkage, complete linkage tends to prefer what kind of clusters?", [opt("A", "Long chained clusters connected by any close bridge"), opt("B", "More compact clusters because it cares about the farthest cross-cluster pair"), opt("C", "Clusters with the largest principal component variance"), opt("D", "Clusters defined only by centroid proximity")], "B", "Complete linkage uses the farthest point pair between clusters, so it penalizes elongated merges and tends to favor tighter, more compact clusters."),
        q("final-c-03", "unsupervised-learning", "Hard", "Initialization sensitivity", "Why does K-means++ or other smarter initialization often improve K-means behavior?", [opt("A", "It removes the need to choose k"), opt("B", "It reduces sensitivity to poor initial centroids and often leads to better local optima"), opt("C", "It turns K-means into a hierarchical method"), opt("D", "It guarantees the global minimum of the objective")], "B", "K-means is not globally convex in the assignments and centroids jointly, so initialization matters. Better seeding reduces the chance of landing in especially poor local solutions."),
        q("final-c-04", "unsupervised-learning", "Hard", "Variance versus separation", "Which statement is the best caution when interpreting PCA dimensions?", [opt("A", "High variance always means high predictive or clustering usefulness"), opt("B", "A low-variance direction can still carry critical structure for separation or decision-making"), opt("C", "Low-variance directions are always noise by definition"), opt("D", "PCA components are ordered by label accuracy")], "B", "Variance alone does not equal usefulness for every task. Important discriminatory structure can live in directions that explain relatively little total variance."),
        q("final-c-05", "unsupervised-learning", "Medium", "t-SNE usage", "For which purpose is t-SNE usually most appropriate?", [opt("A", "As a first-choice production feature extractor for every downstream model"), opt("B", "For exploratory visualization of neighborhood structure in high-dimensional data"), opt("C", "For learning a convex decision boundary"), opt("D", "For replacing all clustering algorithms")], "B", "t-SNE is primarily a visualization tool. It helps reveal local neighborhoods in two or three dimensions, but its embeddings are not meant to be interpreted as stable global geometric maps."),
        q("final-c-06", "unsupervised-learning", "Hard", "Distance concentration", "Why do practitioners become cautious about naive Euclidean distance in very high-dimensional spaces?", [opt("A", "Because Euclidean distance cannot be computed beyond three dimensions"), opt("B", "Because many points can become similarly distant, making nearest and farthest neighbors less distinguishable"), opt("C", "Because high dimension automatically makes all clusters spherical"), opt("D", "Because high dimension forces PCA to return only one component")], "B", "In high dimensions, distance concentration can reduce contrast between near and far points. That weakens the intuitive geometry many distance-based algorithms rely on."),

        q("final-c-07", "neural-networks-foundations", "Hard", "Initialization purpose", "Why are initialization schemes such as Xavier or He initialization useful?", [opt("A", "They help keep activations and gradients in numerically reasonable ranges across layers at the start of training"), opt("B", "They guarantee that the loss surface becomes convex"), opt("C", "They remove the need for bias terms"), opt("D", "They are only needed for linear regression, not deep networks")], "A", "Poor initialization can make activations or gradients blow up or vanish before training even begins effectively. Modern initialization schemes aim to preserve signal scale as it moves through the network."),
        q("final-c-08", "neural-networks-foundations", "Hard", "Cross-entropy intuition", "Why is softmax plus cross-entropy often preferred over mean squared error for ordinary multiclass classification?", [opt("A", "Because it matches the probabilistic interpretation of class distributions and gives more appropriate gradients for classification"), opt("B", "Because MSE cannot be differentiated"), opt("C", "Because cross-entropy only works when there are two classes"), opt("D", "Because softmax outputs are linear in the logits")], "A", "Softmax plus cross-entropy aligns directly with likelihood-based classification. In practice it usually gives cleaner gradients and better learning behavior than treating class prediction like ordinary numeric regression."),
        q("final-c-09", "neural-networks-foundations", "Medium", "L2 regularization", "What is the usual effect of L2 weight decay?", [opt("A", "It encourages excessively large weights to improve memorization"), opt("B", "It penalizes large weights and often promotes smoother, less overfit solutions"), opt("C", "It replaces gradient descent with clustering"), opt("D", "It eliminates the training-validation split")], "B", "L2 regularization adds a penalty on large parameter values, nudging the optimizer toward smaller weights. This can reduce overfitting and stabilize decision boundaries."),
        q("final-c-10", "neural-networks-foundations", "Medium", "Data splits", "What is the cleanest role split among train, validation, and test sets?", [opt("A", "Train for fitting, validation for model or hyperparameter decisions, test for final unbiased evaluation"), opt("B", "Train for evaluation, validation for fitting, test for augmentation"), opt("C", "Train and validation are interchangeable, and test is optional"), opt("D", "Validation exists only for clustering")], "A", "The training set updates model parameters, the validation set supports selection decisions, and the test set is held back for the final estimate of generalization after decisions are complete."),
        q("final-c-11", "neural-networks-foundations", "Medium", "Underfitting diagnosis", "Which pattern most strongly suggests underfitting?", [opt("A", "Training loss is low and validation loss is much higher"), opt("B", "Both training and validation performance remain poor"), opt("C", "Validation performance is better than training performance"), opt("D", "The network uses dropout during training")], "B", "If the model cannot fit the training data well and also fails on validation, the model is usually too weak, poorly optimized, or using representations that are not expressive enough."),
        q("final-c-12", "neural-networks-foundations", "Hard", "Batch size tradeoff", "What is a realistic tradeoff when increasing batch size substantially?", [opt("A", "Larger batches can improve hardware efficiency but may reduce the gradient noise that sometimes helps optimization and generalization"), opt("B", "Larger batches always guarantee better final accuracy"), opt("C", "Larger batches eliminate the need for learning-rate tuning"), opt("D", "Larger batches stop backpropagation from working")], "A", "Large batches can be fast and stable on accelerators, but they also change optimization dynamics. In some problems, less noisy gradients are not always better for final generalization."),

        q("final-c-13", "convolutional-networks", "Medium", "Output channels", "In a standard convolution layer, what determines the number of output channels?", [opt("A", "The input width"), opt("B", "The number of filters"), opt("C", "The padding size only"), opt("D", "The pooling window")], "B", "Each learned filter produces one output feature map. Therefore the number of filters equals the number of output channels."),
        q("final-c-14", "convolutional-networks", "Hard", "Global average pooling", "Why might a model use global average pooling near the end instead of flattening into a huge dense layer?", [opt("A", "To increase parameter count dramatically"), opt("B", "To reduce parameters and encourage channel-level summary features rather than position-specific memorization"), opt("C", "To make the network recurrent"), opt("D", "To remove all convolution operations earlier in the network")], "B", "Global average pooling compresses each feature map into one summary value, reducing parameters and the risk of large fully connected heads memorizing spatial idiosyncrasies."),
        q("final-c-15", "convolutional-networks", "Hard", "Identity mapping", "Why is it useful that a residual block can easily approximate the identity mapping?", [opt("A", "Because then adding the block never changes memory usage"), opt("B", "Because if a deeper transformation is not helpful yet, the network can at least preserve the signal instead of degrading it"), opt("C", "Because identity mappings eliminate nonlinearities entirely"), opt("D", "Because the model no longer needs labels")], "B", "Residual connections make it easier for extra layers to learn 'do no harm' behavior by preserving the input through a skip path. This reduces the optimization burden of very deep networks."),
        q("final-c-16", "convolutional-networks", "Hard", "Bottleneck design", "Why are 1 x 1 convolutions often used before expensive 3 x 3 convolutions in bottleneck blocks?", [opt("A", "To increase spatial size before pooling"), opt("B", "To reduce channel dimension and therefore reduce the cost of the following spatial convolution"), opt("C", "To destroy all color information"), opt("D", "To replace the need for skip connections")], "B", "A 3 x 3 convolution becomes cheaper when it processes fewer input channels. The preceding 1 x 1 layer can project into a narrower channel space first."),
        q("final-c-17", "convolutional-networks", "Medium", "Fine-tuning choice", "When is full fine-tuning of a pretrained visual backbone more attractive than freezing most layers?", [opt("A", "When the target dataset is larger or meaningfully different from the source domain"), opt("B", "When no labeled target data exists at all"), opt("C", "When the target problem is identical to the source problem and data is tiny"), opt("D", "When you want fewer trainable parameters than freezing provides")], "A", "If the new domain differs enough or sufficient target data is available, adapting more of the pretrained representation can produce better specialization than simply reusing it as-is."),
        q("final-c-18", "convolutional-networks", "Hard", "Stacked 3 x 3 versus 7 x 7", "Why can two or three stacked 3 x 3 convolutions be preferable to one single 7 x 7 convolution?", [opt("A", "They often use fewer parameters for similar receptive field growth and insert extra nonlinearities"), opt("B", "A 7 x 7 convolution cannot be backpropagated"), opt("C", "Stacked 3 x 3 layers forbid residual connections"), opt("D", "A 7 x 7 convolution always reduces the image to one pixel")], "A", "Several small kernels can approximate a large receptive field more economically and with more intermediate nonlinear transformations. This was a major design lesson in modern CNN architectures."),

        q("final-c-19", "recommendation-systems", "Medium", "Explicit versus implicit data", "Which statement best contrasts explicit and implicit feedback?", [opt("A", "Explicit feedback contains direct signals like ratings; implicit feedback comes from behavior such as clicks or watch time"), opt("B", "Explicit feedback is always denser than implicit data"), opt("C", "Implicit feedback is always negative unless clicked"), opt("D", "Only explicit feedback can be modeled with embeddings")], "A", "Ratings, reviews, or likes are direct preference expressions, while clicks, dwell time, purchases, and skips are indirect behavioral traces that must be interpreted more carefully."),
        q("final-c-20", "recommendation-systems", "Hard", "Ranking objective", "Why might a recommender team prefer a ranking-oriented loss over a plain pointwise regression loss?", [opt("A", "Because ranking losses focus more directly on relative order among items, which is closer to the product goal"), opt("B", "Because regression losses cannot be differentiated"), opt("C", "Because ranking losses require no negative examples"), opt("D", "Because pointwise methods cannot use neural networks")], "A", "Users care about what appears near the top, not just about calibrated point predictions in isolation. Ranking-aware objectives more directly optimize relative ordering quality."),
        q("final-c-21", "recommendation-systems", "Medium", "New-item cold start", "Which information source is especially valuable for recommending a brand-new item before interactions accumulate?", [opt("A", "Item content features or metadata"), opt("B", "The item's future click history"), opt("C", "Only user bias terms"), opt("D", "The training accuracy of unrelated recommenders")], "A", "When interaction history is absent, side information such as text, genre, category, or image features is the main way to place a new item meaningfully into the system."),
        q("final-c-22", "recommendation-systems", "Hard", "Candidate-generation recall", "Why is high recall in candidate generation important even if ranking is sophisticated?", [opt("A", "Because the ranker can only sort items that survived retrieval in the first place"), opt("B", "Because recall is the same as latency"), opt("C", "Because a powerful ranker can recover omitted items later"), opt("D", "Because retrieval has no effect on exposure")], "A", "If a relevant item never reaches the ranking stage, no downstream model can rescue it. Retrieval quality therefore constrains the upper bound of final recommendation quality."),
        q("final-c-23", "recommendation-systems", "Hard", "NDCG intuition", "Why can NDCG prefer one ranking over another even when both contain the same relevant items in the top k?", [opt("A", "Because NDCG discounts lower positions and rewards placing important hits earlier"), opt("B", "Because NDCG ignores ranking order completely"), opt("C", "Because NDCG only counts item popularity"), opt("D", "Because NDCG cannot compare two lists of the same length")], "A", "NDCG uses position discounting, so finding relevant items earlier is better. Two lists with the same hits can therefore receive different scores depending on where those hits appear."),
        q("final-c-24", "recommendation-systems", "Hard", "Bias-aware factorization", "In the model r_hat_ui = mu + b_u + b_i + p_u^T q_i, what role does p_u^T q_i play after the bias terms?", [opt("A", "It models interaction between latent user preferences and latent item attributes beyond baseline popularity and generosity effects"), opt("B", "It replaces the global mean so mu is unnecessary"), opt("C", "It computes recall@k directly"), opt("D", "It guarantees explainability in natural language")], "A", "The bias terms capture broad average effects, while the dot product captures personalized structure. That latent interaction term explains why a specific user may like a specific item unusually more or less than baseline expectations suggest."),

        q("final-c-25", "sequence-models", "Medium", "Sequence task types", "Which task is a classic many-to-one sequence problem?", [opt("A", "Machine translation"), opt("B", "Sentiment classification of an entire sentence"), opt("C", "Part-of-speech tagging"), opt("D", "Autoregressive language modeling")], "B", "A many-to-one task maps an input sequence to one output label or score. Sentence sentiment classification is the standard example."),
        q("final-c-26", "sequence-models", "Hard", "Vanishing gradients mechanism", "Why do vanishing gradients often arise in recurrent networks?", [opt("A", "Because the optimizer forgets to normalize the labels"), opt("B", "Because backpropagation multiplies many Jacobians whose singular values can be less than one, shrinking signals over time"), opt("C", "Because recurrence removes all parameters after the first step"), opt("D", "Because attention scores are not available")], "B", "Backpropagating through long sequences means repeatedly multiplying derivatives through time. If those factors are consistently small in norm, the contribution of earlier steps decays exponentially."),
        q("final-c-27", "sequence-models", "Hard", "LSTM write control", "What is the clearest role of the input gate in an LSTM?", [opt("A", "It decides how much new candidate information should be written into the cell state"), opt("B", "It decides the final class label directly"), opt("C", "It computes positional encodings"), opt("D", "It enforces a causal mask")], "A", "The input gate modulates how much of the candidate update enters memory. Together with the forget gate, it controls whether memory is overwritten, preserved, or mixed."),
        q("final-c-28", "sequence-models", "Medium", "Attention normalization", "Why is a softmax applied to attention scores for a given query?", [opt("A", "To convert compatibility scores into normalized weights over keys"), opt("B", "To force each value vector to have unit norm"), opt("C", "To remove all position information"), opt("D", "To make the encoder recurrent")], "A", "Softmax turns raw similarity scores into a nonnegative distribution that sums to one. This lets the model form a weighted combination of value vectors for the query."),
        q("final-c-29", "sequence-models", "Medium", "Order in Transformers", "What problem would a Transformer encoder face if positional information were removed entirely?", [opt("A", "It could no longer tell the difference between different permutations of the same tokens"), opt("B", "It would become impossible to compute dot products"), opt("C", "It would automatically turn into an LSTM"), opt("D", "It would collapse all token embeddings to zero")], "A", "Without position signals, self-attention alone treats token sets without inherent order. Sentences with the same words in different arrangements would look too similar to the model."),
        q("final-c-30", "sequence-models", "Hard", "Path length", "Why is short path length between distant tokens often cited as an advantage of self-attention?", [opt("A", "Because information between distant positions need not pass through a long recurrent chain"), opt("B", "Because it guarantees constant-memory training"), opt("C", "Because it removes the need for embeddings"), opt("D", "Because it makes the model exactly linear")], "A", "Self-attention allows direct token-to-token interaction in one layer. This can make it easier to model long-range relations than architectures that pass information step by step over time."),

        q("final-c-31", "generative-ai", "Medium", "Chat models", "What is still true about a chat assistant model underneath its alignment layers and prompting interface?", [opt("A", "Its base sequence modeling remains grounded in token prediction over context"), opt("B", "It no longer uses probabilities over tokens"), opt("C", "It stops being a neural network during inference"), opt("D", "It predicts entire documents in one irreversible step")], "A", "Even aligned assistants remain sequence models that generate outputs token by token conditioned on context. Chat formatting and alignment alter behavior, but they do not replace the core autoregressive mechanism."),
        q("final-c-32", "generative-ai", "Medium", "Top-k sampling", "How does top-k sampling differ from top-p sampling?", [opt("A", "Top-k keeps a fixed number of highest-probability tokens, while top-p keeps however many are needed to exceed a cumulative probability threshold"), opt("B", "Top-k is deterministic and top-p is always greedy"), opt("C", "Top-k is only for images and top-p only for text"), opt("D", "Top-k changes model weights but top-p does not")], "A", "Top-k truncates by count, while top-p truncates by cumulative mass. Depending on the sharpness of the distribution, top-p may keep fewer or more tokens than a fixed k."),
        q("final-c-33", "generative-ai", "Hard", "LoRA mechanics", "What makes LoRA parameter-efficient?", [opt("A", "It fine-tunes the entire dense weight matrix but compresses the optimizer state only"), opt("B", "It learns low-rank adapter updates instead of updating every base-model parameter directly"), opt("C", "It retrieves only low-rank documents at inference time"), opt("D", "It removes the attention layers from the model")], "B", "LoRA introduces small trainable low-rank matrices whose product approximates a useful update to large weights. The base weights stay frozen, so fine-tuning costs drop substantially."),
        q("final-c-34", "generative-ai", "Hard", "RAG choice", "Why is RAG often preferable to fine-tuning when the main problem is factual freshness or source grounding?", [opt("A", "Because RAG can pull in current external documents at inference time without re-training the model"), opt("B", "Because RAG permanently updates the model's weights after every answer"), opt("C", "Because fine-tuning cannot model language"), opt("D", "Because RAG eliminates hallucinations completely")], "A", "If knowledge changes often, updating weights repeatedly is expensive and slow. Retrieval can provide fresh or source-backed context at the moment of answering, which is often a better fit for freshness."),
        q("final-c-35", "generative-ai", "Hard", "Evaluation beyond fluency", "Why is fluent text alone not enough to evaluate a generative AI system?", [opt("A", "Because strong systems must also be judged on correctness, task success, grounding, and safety, not just surface smoothness"), opt("B", "Because fluency is unrelated to language modeling"), opt("C", "Because only image metrics matter"), opt("D", "Because human evaluation cannot be used for generative systems")], "A", "A polished answer can still be wrong, unsafe, or unhelpful. Good evaluation therefore combines surface quality with factual, task-based, and policy-relevant criteria."),
        q("final-c-36", "generative-ai", "Hard", "Diffusion intuition", "What is the forward process in a diffusion model mainly doing?", [opt("A", "Gradually adding noise until structured data approaches noise"), opt("B", "Choosing the most likely next token greedily"), opt("C", "Compressing the training set into two latent factors"), opt("D", "Ranking retrieved documents by semantic similarity")], "A", "The forward process progressively corrupts data with noise. Learning then focuses on reversing that corruption through iterative denoising."),
      ],
    },
  ];

  window.STUDY_DATA = window.STUDY_DATA || {};
  window.STUDY_DATA.exams = exams;

  const topicLabels = Object.fromEntries((window.STUDY_DATA.chapters || []).map((chapter) => [chapter.slug, chapter.shortTitle]));
  const examSearchRecords = exams.flatMap((exam) =>
    exam.questions.map((question, index) => ({
      kind: "exam question",
      topic: question.topic,
      title: `${exam.title} - Q${index + 1}`,
      body: `${question.prompt} ${question.focus}. ${question.explanation}`,
      target: {
        view: "exams",
        exam: exam.id,
        question: question.id,
        topic: question.topic,
        label: topicLabels[question.topic] || question.topic,
      },
    })),
  );
  window.STUDY_DATA.searchIndex = [...(window.STUDY_DATA.searchIndex || []), ...examSearchRecords];
})();
